### PR TITLE
Add support for URL "suffix" to access certain APIs that, eg, uses trailling-slashes at URLs

### PR DESCRIPTION
**Pull request by osantana**

### CODE REVIEW

**Comment by redodo** [comment]
This is a nice addition. However, the current implementation is not consistent with the current approach of configuration in Tortilla.

So, about how it currently works. Every Wrap object has a config dict. The default values are `None`, or in one case, `False`. When the request is initiated, the options will be merged with the Wrap's configuration into a request-specific config dict that's passed and updated down the chain. Basically, when a value is `None` it'll be overwritten.

Config parameters are present in a couple of places:

* parameter of `Wrap.__init__`
* implicitly in the `**options` parameter of `Wrap.request`
* parameter of `Client.request`

This is all done this way to make configuration as dynamic as possible. Different sub-wraps can have different configuration parameters while overloading values as the default.

There is a small [doc](https://github.com/redodo/tortilla/blob/develop/docs/tortilla/configuration.rst) about this in the develop branch, but it doesn't go into much detail.

I would say that this approach has outgrown itself and there should be a class-based implementation that handles this in the background. Something like a cascading dictionary. But, that's currently not in there yet.

I have accepted the PR and I will update the code to conform to the existing structure.

**Comment by redodo** [comment]
I noticed btw that `Wrap.url` doesn't take extension into account. Also, I removed the suffix addition in that method because it would generate URLs like `test//hello//world/` when the suffix option is set for an entire API.

**Comment by osantana** [comment]
> So, about how it currently works. Every Wrap object has a config dict.

Ok. Now I really understand how config dict works. :) Next time I'll use it correctly :)

I've some time to work on tortilla next days... Tell me if you need some help in anything (I'm not so good with documentation because I'm not a fluent in english).

**Comment by redodo** [comment]
No problem. :)

Feel free to work on anything that you think should be improved. If a PR looks good, I'll accept it.

**Comment by shahin** [comment]
@redodo any chance you could release 0.4.3 on pypi to include this patch in the package? We'd love to use it, but installing via Github involves some infrastructure overhead for us.

**Pull request merged**
