### PR TITLE
response and request formats can be specified individually

### PR DESCRIPTION
**Pull request by guglielmo**

### CODE REVIEW

**Comment by hbredin** [comment]
I like the idea but the proposed change is backward-incompatible (as it removes `format` optional argument).

You could go with something like:

```python
def request(..., format='json', req_format=None, resp_format=None, ...):
    ...
    if req_format is None:
        req_format = format
    if resp_format is None:
        resp_format = format
    ...
```

This does not change the previous behavior...
What do you think?

**Comment by redodo** [comment]
Yeah, this would be a great idea to implement.

Another way of allowing for this functionality with backwards compatibility is this:

```python
example.endpoint.get(format=('xml', 'json'))
```

Where the first item is the request format and the second is the response format. The implementation of `request()` would be:

```python
def request([...], format='json', [...]):
    if type(format) in (list, tuple) and len(format) == 2:
        req_format = format[0]
        resp_format = format[1]
    else:
        req_format = resp_format = format
```

I'm not sure if this would be too implicit, so I would like you guys' opinion on this.

**Comment by hbredin** [comment]
I like your (@redodo's) implementation better as it does not add yet another parameter to `request`.

**Comment by guglielmo** [comment]
I've implemented @redodo's tuple format. It's a bit implicit, but the use case is tight. I've modified the documentation of the request method, to explain this as clearly as possible, too.

**Comment by redodo** [comment]
Awesome, thanks. :+1:

**Pull request merged**
